workflow:
  phenotype_dir: "sensitivity/metadata/phenotypes"
  phenotype_list: "sensitivity/metadata/phenotype_list.txt"
  ivw_output_dir: "/workspace/ivw-ld"
  mrlink2_output_dir: "/workspace/mrlink2"
mr_singularity_image: "/g/data/fy54/analysis/tenk10k-causal/containers/mr.sif"
key_files:
  smr_results: "/g/data/fy54/analysis/tenk10k-causal/results/aggregate/tenk10k_phase1_sensitivity.msmr.parquet.gz"
  eqtl_dir: "/g/data/fy54/results/eqtl/saige_qtl/december24_freeze"
container_paths:
  smr_results: "/data/results/aggregate/tenk10k_phase1_sensitivity.msmr.parquet.gz"
  sensitivity_smr_results: "/data/results/sensitivity/smr/tenk10k_phase1/tenk10k_phase1_sensitivity.msmr.parquet.gz"
  snp_smr_results: "/data/results/sensitivity/smr/tenk10k_phase1/tenk10k_phase1_sensitivity.snps4msmr.parquet.gz"
  probe_smr_results: "/data/results/sensitivity/smr/tenk10k_phase1/tenk10k_phase1_sensitivity.prbregion4msmr.parquet.gz"
  ma_dir: "/data/resources/ma"
cluster:
  mkdir -p logs/pbs &&
  qsub
    -q {resources.queue}
    -l ncpus={resources.ncpus}
    -l mem={resources.mem}
    -l walltime={resources.time}
    -l jobfs={resources.jobfs}
    -l storage=gdata/fy54
    -l wd
    -P fy54
    -o logs/pbs/{rule}_{wildcards}.o
    -e logs/pbs/{rule}_{wildcards}.e
    -N {rule}.{wildcards}
default-resources:
  - ncpus=1
  - mem="4G"
  - time="01:00:00"
  - jobfs="1G"
  - queue="normal"
jobs: 30
latency-wait: 120
use-singularity: true
singularity-args: >-
  --bind /g/data/fy54/analysis/tenk10k-causal:/data,/g/data/fy54/genotypes/common_variants/2024-12_Freeze/plink:/genotypes,/scratch/fy54/as8574/analysis/tenk10k-causal:/workspace,/g/data/fy54/results/eqtl/saige_qtl/december24_freeze:/eqtl
use-conda: true
rerun-incomplete: true
