# Date: 07/04/2026 
# Purpose: Save intermediate files of msmr and coloc results for crohns_case_study scripts. Annotate them with evidence of disease
# association from external sources 
# Part i: Create annotation functions
# Part 1: Annotate eQTLGen significant - raw 
# Part 2: Annotate external source gene lists (for Crohn's results only) - raw, crohns 
# Part 3: Annotate opposite direction of effect and cell type specific - mr_sens sig all traits and mr_sens sig crohns
# Part 4: Save annotated raw, sig, for all traits and crohns, and raw eqtlgen 

#########################################################################################
# Interactive job information 
# qsub -I -q normal -P fy54 -l ncpus=2,storage=gdata/fy54+gdata/ei56,mem=32GB -l jobfs=100GB
# cd /g/data/fy54/rt3501/repos/tenk10k-causal/
# conda activate tidyverse
# R
#########################################################################################

library(data.table)
library(tidyverse)
library(here)
library(arrow)

crohns_dir <- here("resources/crohns_case_study/postprocess")

# note that preprocess_strict.R reads in an intermediate file for df_tenk10k_msmr generated by the snakemake workflow: https://github.com/powellgenomicslab/tenk10k-causal/blob/main/workflow/rules/snakescripts/preprocess/tenk10k_phase1.v2.R#L108
# source preprocess script to get df_coloc, df_tenk10k_msmr (with sensitivity and coloc annotation) and df_eqtlgen_msmr & df_gene_annot dataframe (gtf file)
source(here("scripts/preprocess_strict.R"))

# Save df_coloc 
df_coloc <- df_coloc %>% rename("probeID" = gene)
df_coloc <- df_coloc %>%
    left_join(df_gene_annot %>% select(hgnc_symbol, ensembl_gene_id), by = c("probeID" = "ensembl_gene_id")) %>%
    rename(Gene = hgnc_symbol)

saveRDS(df_coloc, paste0(crohns_dir,"/df_coloc.RDS"))

# Save eqtlgen - raw, all traits
saveRDS(df_msmr_eqtlgen, paste0(crohns_dir,"/eqtlgen_alltraits_raw.RDS"))

############# ---------------------
# if there's a mixture of positive and negative (DISCORDANT), the var of the sign != 0

# Only applicable on significant results 
annotate_opp_dir_gene <- function(df){
    df %>% 
    group_by(phenotype, probeID) %>% 
    mutate(discordant_bSMR = var(sign(b_SMR)) != 0) %>% 
    ungroup()
}

############# ---------------------
# Only applicable on significant results 
annotate_ct_spec <- function(df){
    df %>% 
    group_by(phenotype, probeID) %>%
    mutate(ct_spec = n_distinct(cell_type) == 1) %>%
    ungroup()
}

############# ---------------------
# Prep eqtlgen results 
df_msmr_eqtlgen <- df_msmr_eqtlgen %>%
    select(-Gene) %>%
    left_join(df_gene_annot %>% select(hgnc_symbol, ensembl_gene_id), by = c("probeID" = "ensembl_gene_id")) %>%
    rename(Gene = hgnc_symbol)
# Create an eQTL sig boolean table 
df_msmr_eqtlgen_sig_annot_df <- df_msmr_eqtlgen %>%
    filter(sig == TRUE) %>%
    select(Gene, probeID, phenotype, sig) %>%
    rename(eqtlgen_sig = sig)

# Applicable to sig or non-sig results 
annotate_eqtlgen_sig <- function(df){
    df %>% 
    left_join(df_msmr_eqtlgen_sig_annot_df, by = join_by(Gene, probeID, phenotype))
}

############# ---------------------
# Create a function to annotate external sources df 
external_source_df <- readRDS(here("resources/crohns_case_study/crohns_relevant_gene_lists/external_source_gene_annot_df.RDS"))
# Applicable to sig or non-sig results 
annotate_ext_source_df <- function(df, annotation){
    left_join(df, annotation, by = c("Gene" = "Gene", "probeID" = "ensembl_gene_id"))
}
############# ---------------------


################################ All annotation functions made 

# Annotate raw, all traits with eqtlsig membership 
df_msmr_tenk10k_annotated <- annotate_eqtlgen_sig(df_msmr_tenk10k)
# Annotate raw, crohns with external source membership 
df_msmr_tenk10k_annotated_crohns <- df_msmr_tenk10k_annotated %>% filter(phenotype == "crohns") %>% annotate_ext_source_df(external_source_df)

# Annotate sig, all traits with opposite directions of effect and cell type specific (informal definition)
df_msmr_tenk10k_sig_annotated <- df_msmr_tenk10k_annotated %>%
    filter(mr_sens_coloc == TRUE) %>%
    annotate_opp_dir_gene() %>%
    annotate_ct_spec()

df_msmr_tenk10k_sig_annotated_crohns <- df_msmr_tenk10k_annotated_crohns %>%
    filter(mr_sens_coloc == TRUE) %>%
    annotate_opp_dir_gene() %>%
    annotate_ct_spec()

# Save annotated all traits - raw and sig 
saveRDS(df_msmr_tenk10k_annotated, paste0(crohns_dir, "/tenk_alltraits_raw.RDS"))
saveRDS(df_msmr_tenk10k_sig_annotated, paste0(crohns_dir, "/tenk_alltraits_sig.RDS"))

# Save annotated crohns - raw and sig 
saveRDS(df_msmr_tenk10k_annotated_crohns, paste0(crohns_dir,"/tenk_crohns_raw.RDS"))
saveRDS(df_msmr_tenk10k_sig_annotated_crohns, paste0(crohns_dir,"/tenk_crohns_sig.RDS"))


